apiVersion: apps/v1
kind: Deployment
metadata:
    name: web_developer_web
    annotations:
        kubernetes.io/change-cause: "initial commit"
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nuxt
            env: dev
    revisonHistoryLimit: 10
    strategy:
        rollingUpdate:
            type: rollingUpdate
            maxSurge: 2
            MacUnavailable: 1
    template:
        metadata:
            name: web_developer_web
            labels:
                app:nuxt
                env:dev
        spec:
            containers:
            - name: web_developer_web
              image: [後で修正]

---
apiVersion: v1
kind: Service
metadata:
    name: web_developer_web
spec:
    type: ClusterIP
    clusterIP: ""
    ports:
    - port: 80
      targetPort:3000
    selector:
      app:nuxt
      env:dev

